meta: lower requirement to Python 3.6
cptpcrd/pyprctl pull request #1
Opened 2021-06-10 07:45 UTC by martijnthe

`pyprctl` seems to work fine on Python 3.6, granted the `dataclasses` backport is installed as well.

This PR updates the dependency information to allow `pyctrl` to be installed on Python 3.6.

2021-06-10 22:26 UTC, cptpcrd requested changes
LGTM except for one thing.

I'm not 100% sure why the CI job is failing, but it isn't a blocker. I'll take a look after merging.

2021-06-10 22:26 UTC, cptpcrd commented on setup.cfg
> -python_requires = >=3.7
Please add the Python 3.6 classifier under the `[metadata]` section above.

2021-07-10 23:10 UTC, merged

2021-10-25 22:00 UTC, mitar commented
@cptpcrd Any plans to make a release any time soon which would include this?

2021-10-26 23:55 UTC, cptpcrd commented
@mitar just released.

2021-10-27 06:37 UTC, mitar commented
Awesome! Thank you so much!